management:
  endpoints:
    web:
      exposure:
        include: '*'
configuracion:
  texto: Developer
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        slow-call-rate-threshold: '50'
        slow-call-duration-threshold: 2s
        permitted-number-of-calls-in-half-open-state: '4'
        failure-rate-threshold: '50'
        wait-duration-in-open-state: 20s
        sliding-window-size: '6'
    instances:
      items:
        base-config: defecto
  timelimiter:
    instances:
      items:
        base-config: defecto
    configs:
      defecto:
        timeout-duration: 2s
spring:
  application:
    name: msvc-items
  profiles:
    active: dev
config:
  base-url:
    msvc-products: http://msvc-products
server:
  port: ${PORT:0}
